# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ElmLang' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ElmLang

  # pod 'SwiftHEXColors'

  # pod 'Alamofire',
  #   :git => 'https://github.com/Alamofire/Alamofire.git',
  #   :branch => 'swift3'

  # pod 'Font-Awesome-Swift',
  #   :git => 'https://github.com/Vaberer/Font-Awesome-Swift.git',
  #   :branch => 'swift-3'

  target 'ElmLangTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ElmLangUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
