# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ElmLang' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ElmLang
  # pod 'Alamofire',
  #   :git => 'https://github.com/Alamofire/Alamofire.git',
  #   :branch => 'swift3'

  target 'ElmLangTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ElmLangUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
